apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: easybarcodegenerator-com
  namespace: avencera
spec:
  secretName: easybarcodegenerator-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.easybarcodegenerator.com"
  dnsNames:
    - easybarcodegenerator.com
  acme:
    config:
      - dns01:
          provider: cf-dns
        domains:
          - "*.easybarcodegenerator.com"
          - easybarcodegenerator.com
